# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tmcorreia.github.io
baseurl: /QBioImaging
source-code: https://github.com/tmcorreia/QBioImaging

title: QBI Home
email: teresa.correia@kcl.ac.uk
author: Teresa Correia
description: > # Quantitative Bioimaging group at CCMAR MRI Optical Imaging Deep Learning Image Reconstruction Processing 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/TeresaM2Correia
  - title: github
    url: https://github.com/QBioImaging
  - title: send
    url: https://www.ccmar.ualg.pt/users/tmcorreia
